# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: Qinxiu-Local

stages:
- stage: Pre_Commit
  displayName: Pre_Commit
  pool: Azure Pipelines
  jobs:
  - job: Unit_test
    displayName:  Unit_test
    steps:
      - task: Maven@3
        displayName: 'Maven test execution'
        inputs:
          mavenPomFile: 'pom.xml'
          goals: test

  - job: Linter_Check
    displayName:  Linter_Check
    steps:
      - task: Maven@3
        displayName: 'Maven test execution'
        inputs:
          mavenPomFile: 'pom.xml'
          goals: checkstyle:check