# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: Azure Pipelines

stages:
- stage: Pre_Commit
  displayName: Pre_Commit
  jobs:
  - job: Maven_test
    displayName:  Maven_test_Job
    steps:
      - task: Maven@3
        displayName: 'Maven test execution'
        inputs:
          mavenPomFile: 'pom.xml'
          goals: test